# Generated by Django 3.1.6 on 2021-03-06 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketpoint',
            name='currency',
        ),
        migrations.AddField(
            model_name='marketpoint',
            name='exchange_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frm', to='market.currency'),
        ),
        migrations.AddField(
            model_name='marketpoint',
            name='exchange_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to', to='market.currency'),
        ),
    ]
